CREATE TABLE IF NOT EXISTS admin_users (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS firmware_version VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS firmware_filename VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS firmware_md5 VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS firmware_uploaded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS rollout_delay_days INTEGER NOT NULL DEFAULT 0;
